# TODO:
# - install rsync, ..; install zsh if fedora or epel mirrors are defined
- set_fact:
    dist_mirror_rsync: "rsync -rlptDvzvSHPhi --stats --chmod=D755,F644 --delete --delete-after --delete-excluded"

- set_fact:
    _supported_mirrors:
      - centos
      - opensuse
      - elrepo
      - py-modules

- set_fact:
    dist_mirrors: {}
  when: dist_mirrors is undefined

- name: add dist mirror group
  group:
    name: "{{dist_mirrors.group|default(dist_mirrors.user)}}"
    system: yes
  when: >
    dist_mirrors.group is defined or
    dist_mirrors.user is defined

- name: add dist mirror
  user:
    name: "{{dist_mirrors.user}}"
    group: "{{dist_mirrors.group|default(dist_mirrors.user)}}"
    createhome: yes
    home: "{{dist_mirrors.mirror_base}}"
    system: yes
  when: >
    dist_mirrors.user is defined

- name: chown dist mirror directory
  file:
    path: "{{dist_mirrors.mirror_base}}"
    owner: "{{dist_mirrors.user}}"
  when: >
    dist_mirrors.user is defined

- name: create dist-mirror directory
  file:
    state: directory
    path: /usr/lib/dist-mirror
    mode: 0755

- name: configure mirrors
  include_tasks: configure_mirror.yml
  with_dict: "{{dist_mirrors}}"
  loop_control:
    loop_var: mirror
  when: >
    mirror.key in _supported_mirrors or
    (mirror.value.type is defined and
     mirror.value.type in _supported_mirrors)
